conn.query('CREATE DATABASE IF NOT EXISTS `matcha`')

conn.query('USE `matcha`')

conn.query(`CREATE TABLE IF NOT EXISTS users (id INT AUTO_INCREMENT PRIMARY KEY, username VARCHAR(255), firstname VARCHAR(255), lastname VARCHAR(255), email VARCHAR(255), password VARCHAR(255), vkey VARCHAR(10), activate INT DEFAULT 0, gender VARCHAR(255), age INT DEFAULT 0, bio TEXT, score INT DEFAULT 0 ,orientation VARCHAR(255), profileImg VARCHAR(255) DEFAULT '/img/default.jpg')`)

conn.query(`CREATE TABLE IF NOT EXISTS tags ( id INT AUTO_INCREMENT PRIMARY KEY, user_id INT, tag VARCHAR(255))`)

conn.query(`CREATE TABLE IF NOT EXISTS likes (id INT AUTO_INCREMENT PRIMARY KEY, user_id INT NOT NULL, secondUsrId INT NOT NULL)`)

conn.query(`CREATE TABLE IF NOT EXISTS chat (id INT AUTO_INCREMENT PRIMARY KEY,  message TEXT, user_id INT NOT NULL, secondUsrId INT NOT NULL, date DATETIME DEFAULT CURRENT_TIMESTAMP)`)

conn.query(`CREATE TABLE IF NOT EXISTS notifications (id INT AUTO_INCREMENT PRIMARY KEY,user_id INT NOT NULL, secondUsrId INT NOT NULL, notif TEXT, date DATETIME DEFAULT CURRENT_TIMESTAMP)`)
 
conn.query(`CREATE TABLE IF NOT EXISTS visits (id INT AUTO_INCREMENT PRIMARY KEY, user_id INT NOT NULL, secondUsrId INT NOT NULL, date DATETIME DEFAULT CURRENT_TIMESTAMP)` )

conn.query(`CREATE TABLE IF NOT EXISTS block (id INT AUTO_INCREMENT PRIMARY KEY, user_id INT NOT NULL, secondUsrId INT NOT NULL)`)